name       : python-dill
version    : 0.3.4
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/d/dill/dill-0.3.4.zip : 9f9734205146b2b353ab3fec9af0070237b6ddae78452af83d2fca84d739e675
homepage   : https://github.com/uqfoundation/dill
license    : BSD-3-Clause
component  : programming.python
summary    : serialize all of python
description: |
    dill extends python's pickle module for serializing and de-serializing python objects to the majority of the built-in python types. Serialization is the process of converting an object to a byte stream, and the inverse of which is converting a byte stream back to a python object hierarchy.
build      : |
    %python3_setup
install    : |
    %python3_install
