name       : python-dill
version    : 0.3.5.1
release    : 3
source     :
    - https://github.com/uqfoundation/dill/releases/download/dill-0.3.5.1/dill-0.3.5.1.tar.gz : d75e41f3eff1eee599d738e76ba8f4ad98ea229db8b085318aa2b3333a208c86
homepage   : https://github.com/uqfoundation/dill
license    : BSD-3-Clause
component  : programming.python
summary    : serialize all of python
description: |
    dill extends python's pickle module for serializing and de-serializing python objects to the majority of the built-in python types. Serialization is the process of converting an object to a byte stream, and the inverse of which is converting a byte stream back to a python object hierarchy.
build      : |
    %python3_setup
install    : |
    %python3_install
